name: disablecraft
main: me.tabr.disablecraft.DCMain
version: 1.1
author: tabr
commands:
  disablecraft:
    aliases: [dc]
    description: shows list of commands
    usage: </disablecraft [command]>
